app = 'usuario-snowy-harborwave-2015'
primary_region = 'dfw'

[build]
  image = 'n8nio/n8n:latest'

[env]
  GENERIC_TIMEZONE = 'America/Bogota'
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS = 'true'
  N8N_HOST = 'usuario-snowy-harborwave-2015.fly.dev'
  N8N_PORT = '5678'
  N8N_PROTOCOL = 'https'
  TZ = 'America/Bogota'
  WEBHOOK_URL = 'https://usuario-snowy-harborwave-2015.fly.dev/'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = 'n8n_data'
  destination = '/home/node/.n8n'
  initial_size = '1gb'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
